### ISSUE TITLE
Facebook hesabı kaldırma

### ISSUE THREAD

**Issue by tinerci** [Hasokeyk/instagram-pro#2]
Merhaba, SMM panel için geliştirdiğimiz api sistemimiz var. fakat hesaplardaki facebook kaldırma işlemini yapamadık. facebook account remover apisini bizimle paylaşma şansınız varmı acaba ?

**Comment by Hasokeyk** [comment]
Merhabalar,

Maalesef kütüphanenin önemli özelliklerinden biri olduğu için kodu ayrıca paylaşamıyorum.

**Comment by tinerci** [comment]
> Merhabalar,
> 
> Maalesef kütüphanenin önemli özelliklerinden biri olduğu için kodu ayrıca paylaşamıyorum.

Sadece api url sini atma şansınız yokmu?
Bkz: i.instagram.com/apiv1/vs
