### ISSUE TITLE
buy linssecc

### ISSUE THREAD

**Issue by abolfazllover** [Hasokeyk/instagram-pro#4]
Hello, good time, how can I receive a license from you?

**Comment by Hasokeyk** [comment]
Contact has been made by e-mail.

**Comment by osman231** [comment]
hocam lisans için bilgi verebilir misiniz

**Comment by Hasokeyk** [comment]
Merhabalar, Şu an kütüphane çalışmıyor ve uzun zamandır güncellenmedi. O yüzden şu an destek veremiyorum.
